### ISSUE TITLE
type 'List<dynamic>' is not a subtype of type 'List<SylphDevice>'

### ISSUE THREAD

**Issue by vishna** [mmcc007/sylph#63]
got myself to this stacktrace on `0.4.0`

```
Running tests concurrently on iOS and Android pools...
Running test suite 'catalogue tests 1'  in project 'Catalogue App' on pool 'android pool 1'...
Creating new device pool 'android pool 1' ...
Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'List<SylphDevice>'
#0      setupDevicePool (package:sylph/src/device_farm.dart:58:34)
#1      runSylphJob (package:sylph/src/sylph_run.dart:99:26)
<asynchronous suspension>
#2      runSylphJobInIsolate (package:sylph/src/concurrent_jobs.dart:39:27)
<asynchronous suspension>
#3      IsolateRunnerRemote._handleCommand.<anonymous closure> (package:isolate/isolate_runner.dart:298:43)
#4      new Future.sync (dart:async/future.dart:224:31)
#5      IsolateRunnerRemote._handleCommand (package:isolate/isolate_runner.dart:298:17)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by vishna** [comment]
this passes on latest master
`pub global activate -sgit https://github.com/mmcc007/sylph.git`

**Comment by vishna** [comment]
so probably it would make sense to push an update to pub.dev and then close this

**Comment by mmcc007** [comment]
I will release a new version shortly
