### ISSUE TITLE
Cannot use libraries with `path`

### ISSUE THREAD

**Issue by Vanethos** [mmcc007/sylph#73]
If in our `pubspec.yaml` file we have a dependency such as:

```yaml
  tutorial_coach_mark:
    path: /path/to/tutorial_coach_mark
```

The following error is thrown:

```
cp: ./ios/.symlinks/plugins/notification_permissions/example/ios/.symlinks/plugins/notification_permissions: directory causes a cycle
cp: ./path/to/tutorial_coach_mark: No such file or directory
Unhandled exception:
command failed: cmd='cp -r . /tmp/sylph/test_bundle/flutter_app'
#0      cmd (package:sylph/src/utils.dart:43:5)
#1      LocalPackageManager.copy (package:sylph/src/local_packages.dart:103:9)
<asynchronous suspension>
#2      bundleFlutterTests (package:sylph/src/bundle.dart:56:23)
<asynchronous suspension>
#3      sylphRun (package:sylph/src/sylph_run.dart:53:9)
<asynchronous suspension>
#4      main (file:///Users/goncalopalma/.pub-cache/hosted/pub.dartlang.org/sylph-0.5.0/bin/main.dart:73:13)
<asynchronous suspension>
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by mmcc007** [comment]
Added fix. Please try it out with
```
git clone https://github.com/mmcc007/sylph.git
cd sylph
git checkout #73_absolute_path
pub global activate --source path .
```
and confirm it works.
