### ISSUE TITLE
Flutter version used is not the latest

### ISSUE THREAD

**Issue by fvisticot** [mmcc007/sylph#82]
When tests occurs I can see the following logs:
How to get the last stable version (v1.9.1+hotfix.6) ?

[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.2 at /home/device-farm/flutter
    • Framework revision 2d2a1ffec9 (3 months ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

**Comment by mmcc007** [comment]
`flutter upgrade` should do it

**Comment by fvisticot** [comment]
Agree but where to change / add the flutter upgrade command ?

**Comment by mmcc007** [comment]
You can do it from anywhere. Not required to be in a project.

**Comment by fvisticot** [comment]
You mean I need to do the command on my laptop ? where can be the pb ?
Can you please explain how your solution is working ?

When I execute flutter doctor I get version v1.9.1+hotfix.6

`@MacBook-Pro-de-frederic flutter_aws_test % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale fr-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.1)
[✓] Connected device (2 available)
`

**Comment by mmcc007** [comment]
The version of flutter running on Device Farm is set [here](https://github.com/mmcc007/sylph/blob/908b4ab6fb53275f3236ca7746d1bb6e294c4eb4/lib/resources/test_spec.yaml#L32). 

Will upgrade in next release. In the meantime it's possible to clone the repo and change it.

**Comment by chinnonsantos** [comment]
> The version of flutter running on Device Farm is set [here](https://github.com/mmcc007/sylph/blob/908b4ab6fb53275f3236ca7746d1bb6e294c4eb4/lib/resources/test_spec.yaml#L32).
> 
> Will upgrade in next release. In the meantime it's possible to clone the repo and change it.

Firstly congratulations for the excelente job with sylph 👏👏👏

I will send a PR to help you about this, but I'm using sylph for shortly time to can greats changes in the library code. Change this variable is simple...

Is it possible define this variable **`FLUTTER_VERSION`** in the **`sylph.yaml`** file for custom Flutter version (and channel) to every project?

I will happy to define **`channel beta`** for some projects but not for all, can you understand me? I very happy so use your library, it's amazing!!! 😍

**Comment by chinnonsantos** [comment]
@mmcc007 

Just updating the Flutter version isn't works! 

![Screenshot from 2019-12-18 17-48-50](https://user-images.githubusercontent.com/3258293/71122215-d3415b00-21be-11ea-9b71-921d5c35f527.png)

I can updating the flutter version 

```shell
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/device-farm/flutter
    • Framework revision 27321ebbad (8 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
```

I tried many things, but always has an error in Flutter (See my commits...)

```shell
Running "flutter pub get" in flutter_app...                     
Because every version of flutter_driver from sdk depends on intl 0.15.8 and nudemo depends on intl ^0.16.0, flutter_driver from sdk is forbidden.

So, because nudemo depends on flutter_driver any from sdk, version solving failed.
pub get failed (1)
Most recent command failed with error code: 1
```

And then...

```shell
Running "flutter pub get" in flutter_app...                         9.7s

Sending crash report to Google.
Crash report sent (report ID: 8cbe647aa948df14)
Oops; flutter has exited unexpectedly.
Crash report written to /tmp/scratchyy4UFP.scratch/test-packageJvlll9/flutter_app/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
Most recent command failed with error code: 1
```

And then...

```shell
Running "flutter pub get" in flutter_app...                         9.4s

Sending crash report to Google.
Crash report sent (report ID: 058dd01be7da2052)
Oops; flutter has exited unexpectedly.
Crash report written to /tmp/scratchbR6V9A.scratch/test-packagem0ZujW/flutter_app/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
Most recent command failed with error code: 1
```

And then...

```shell
* failed to start daemon
adb: failed to check server version: cannot connect to daemon
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/device-farm/flutter
    • Framework revision 27321ebbad (8 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/device-farm/android-sdk-linux
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/device-farm/android-sdk-linux
    • Java binary at: /usr/lib/jvm/jdk1.8.0_65/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: /home/device-farm/android-sdk-linux/platform-tools/adb
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
      #1      getAdbDevices (package:flutter_tools/src/android/android_device.dart:731:5)
      #2      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:65:53)
      #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:285:52)
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:140:46)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:851:54)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1126:13)
      #8      _CustomZone.run (dart:async/zone.dart:1023:19)
      #9      _runZoned (dart:async/zone.dart:1518:10)
      #10     runZoned (dart:async/zone.dart:1502:12)
      #11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #12     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:158:9)
      #13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
      #14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:241:24)
      #16     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
      #17     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #18     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:45:42)
      #19     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
      #20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
      #21     _rootRunUnary (dart:async/zone.dart:1134:38)
      #22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      #23     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
      #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
      #25     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
      #26     Future._completeWithValue (dart:async/future_impl.dart:524:5)
      #27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
      #28     _rootRun (dart:async/zone.dart:1126:13)
      #29     _CustomZone.run (dart:async/zone.dart:1023:19)
      #30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
      #32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
      #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
      #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)


! Doctor found issues in 2 categories.
```

And others...

**Comment by chinnonsantos** [comment]
I install the custom sylph library like this:

**`pub global activate --overwrite --source git https://github.com/chinnonsantos/sylph.git`**

**Comment by mmcc007** [comment]
@chinnonsantos These look like issues unrelated to sylph. I expect you should be getting similar results on a similar local linux machine. 

BTW: you may be able to fix the `flutter pub get` error by updating your pubspec.yaml with something like:
```
  intl: ">=0.15.0 <1.0.0"
```

**Comment by chinnonsantos** [comment]
In fact the [`intl`](https://pub.dev/packages/intl) plugin caused a problem with testing, I could fix this using:

`intl: any`

No `pubspec.lock` indicates that Flutter has decided to use version `0.16.0`, but using the same Flutter version **v1.9.1+hotfix.2 (out of date)**.

When I updated the Flutter version to last version **v1.12.13+hotfix.5**, there is an unknown crash after `flutter pub get`:

```
Running "flutter pub get" in flutter_app...                         9.4s

Sending crash report to Google.
Crash report sent (report ID: 058dd01be7da2052)
Oops; flutter has exited unexpectedly.
Crash report written to /tmp/scratchbR6V9A.scratch/test-packagem0ZujW/flutter_app/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
Most recent command failed with error code: 1
```
I think this a problem related between the **last version** of Flutter and **`intl` plugin**. So, like I need the `intl` I give up the update at moment.

Thanks for the help. **I will try update again in future...**

**Comment by mmcc007** [comment]
Should be fixed now. Try it out with:
```
git clone https://github.com/mmcc007/sylph.git
pub global activate -s path sylph
```
